# Generated by Django 3.0.3 on 2020-04-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='on_date',
            new_name='created_on',
        ),
    ]
